USE MainDatabase
GO
CREATE TABLE HistoryOfBank (
    Id INT PRIMARY KEY IDENTITY(1, 1),
    UserEmail VARCHAR(40) NOT NULL CONSTRAINT FK_HistoryOfBank_Users FOREIGN KEY REFERENCES Users(Email) ON DELETE CASCADE,
    OperationDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    OperationType VARCHAR(30) NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    FromWhom VARCHAR(40) DEFAULT NULL,
    ToWhom VARCHAR(40) DEFAULT NULL
);