CREATE DATABASE MainDatabase
GO
USE MainDatabase
GO
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    [Name] NVARCHAR(20) NOT NULL,
    [Surname] NVARCHAR(20) NOT NULL,
    [Email] VARCHAR(40) NOT NULL UNIQUE,
    [PhoneNumber] VARCHAR(15) NOT NULL UNIQUE,
    [Age] TINYINT NOT NULL CONSTRAINT CH_Age CHECK (Age >= 18 AND Age <= 100),
    [Password] VARCHAR(32) NOT NULL
)