USE MainDatabase
GO
CREATE TABLE Bank (
    Id INT PRIMARY KEY IDENTITY(1, 1),
    UserEmail VARCHAR(40) CONSTRAINT FK_Bank_Users FOREIGN KEY (UserEmail) REFERENCES Users(Email) ON DELETE CASCADE,
    Deposit DECIMAL(18, 2) NOT NULL DEFAULT 0
)